### ISSUE TITLE
Failed loading resources

### ISSUE THREAD

**Issue by andretti1977** [jobtalle/Koi#180]
Hello,
i've built application as you suggested for mac osx, no error logged, everything went smooth, but when launching the app i got a green screen and after a while an alert "Failed loading resources" was shown. After clicking the ok button, alert gets dismissed and "Koi Farm" title appears with fade-in but animation nothing else happens.
MacOs Catalina 10.15.5 on a MacBook Pro (Retina, 15-inch, Mid 2014) with Intel Iris Pro 1536 MB

**Comment by jobtalle** [comment]
Did you clone the translations submodule properly?

**Comment by andretti1977** [comment]
Sorry, i've just found that by my self debugging the app and came here to close the issue 🤦‍♂️
I'm sorry i made you loose some time for something that was an error of mine.
I simply git cloned the main project and then manually cloned the squish submodule manually since you explicitly stated that in the docs, but completely missed the translation one! Again, sorry!
