### ISSUE TITLE
"Failed Loading Resources" Manjaro Linux

### ISSUE THREAD

**Issue by billotronic** [jobtalle/Koi#184]
```
5.9.16-1-MANJARO
node -v
v15.11.0
npm -v
7.6.3
python3 --version
Python 3.9.2

```
All steps complete without error. When executing KoiFarm the window starts but nothing is rendered in it.

https://imgur.com/xrw3kkG.png
https://imgur.com/u35hNbR.png

**Comment by jobtalle** [comment]
Check out issue #180

**Comment by billotronic** [comment]
Holy crap how embarrassing. I'm sorry for the clutter, I did a poor job on due diligence. 

Thank you very much for the very prompt response.
